name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry and deps
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root

      - name: Run test
        run: |
          poetry run pytest -vv
